### ISSUE TITLE
README shows ls as an available command

### ISSUE THREAD

**Issue by theoutlander** [dib-lab/osf-cli#109]
The documentation states 'ls' is a command, whereas it might be 'list' instead.

Secondly, here's an error I get when I run the command:

> Nicks-MacBook-Pro-2:osf-cli theoutlander$ osf ls
usage: osf [-h] [-u USERNAME] [-p PROJECT] [-v]
           {clone,init,fetch,list,upload,remove} ...
osf: error: argument command: invalid choice: 'ls' (choose from 'clone', 'init', 'fetch', 'list', 'upload', 'remove')

The error also fails to mention the order in which the "command" would go in that command.

Just something that might make things clearer for a first time user.

**Comment by ctb** [comment]
thank you!  the docs here

https://osfclient.readthedocs.io/en/stable/cli-usage.html

are what I usually go to - we will fix up the default output to be more
helpful!

**Comment by nkmeyers** [comment]
@theoutlander - gotta "declare" a project w/ -p before using "ls", I think? or , as in bottom of docs link that @ctb sent,  you can set a default project value by using a configuration file in the current directory. To set the username and project ID create .osfcli.config:

[osf]
username = yourOSFaccount@example.com
project = 9zpcy

If the project is private you will need to provide authentication details

Then, after the above is set or stated  you can simply run "osf ls" to list the contents of the [default/current] project.

**Comment by theoutlander** [comment]
@nkmeyers I ran "osf init" and it created a config file with the following:

> [osf]
username = theoutlander
project = osf-test

I'm unclear about the password, but as the project isn't private (I'm assuming), I do not need to enter anything.

As for "osf ls", the command needs to be "osf list" instead. It appears that by default osf is looking for the .osfcli.config file in the folder where you run the command.

**Comment by nkmeyers** [comment]
@theoutlander , here's a public project with just a handful of files https://osf.io/s5e2b/. I've added you to a private project you'll get a link to claim if you want to test against a private one too.

**Comment by betatim** [comment]
[ls is set as an alias](https://github.com/dib-lab/osf-cli/blob/007a1b7a50576e568e1ef446f5e4f20ce30e0f79/osfclient/__main__.py#L73) for list, so it should work, or we don't understand how to use `argparse`. Definitely something to fix.

@theoutlander could you open a new issue regarding only checking the current directory for `.osfcli.config`. Would indeed be useful to also search "upwards". Though knowing how/when to stop is a bit tricky so best to discuss in a new issue.

The password can't be set in a file, you should be prompted for it when `osfclient` needs it. You can also set the `OSF_PASSWORD` environment variable to contain your password which will then be used instead of prompting you for it.

**Comment by theoutlander** [comment]
@betatim https://github.com/dib-lab/osf-cli/issues/110

**Comment by betatim** [comment]
In #121 we figured out that the aliases in `argparse` only seem to work in python and not python2.

With #110 and #121 I think we can close this. Feel free to re-open if needed.
